version: "3.4"

networks:
  mydockerapi-dev:
    driver: bridge

services:
  mydockerapi:
    image: mydockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=germannunez;Password=Abc123;Server=postgres_image;Port=5432;Database=cardb;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      # DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=cardb;username=germannunez;password=Abc123"
    networks:
      - mydockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./mydockerapi/dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_USER=germannunez
      - POSTGRES_PASSWORD=Abc123
      - POSTGRES_DB=cardb
    networks:
      - mydockerapi-dev
volumes:
  db_volume:
